### PR TITLE
chore: Remove local server for dapp

### PR DESCRIPTION
**Pull request by Tbaut**
I figured there's actually quite a lot of code related to this now useless blank page. As Bero already told me, we can visit any page. I went for example.org because it's extremely simple, no js or tracking like google would do.

I did this in a separate PR (but on top of the docs one) to separate concerns. Re-basing had quite a lot of conflicts so I wanted to spare the troubles.

**Short description of work done**
Get rid of any test server code.

### PR Checklist

- [x] I have run linter locally
- [x] I have run unit and integration tests locally
  - [x] Update configuration the newest version (readme and const)
- [x] Rebased to master branch / merged master

### CODE REVIEW

**Comment by Tbaut** [comment]
If any of you has a clue why the build is failing.. although I didn't touch this part at all. That's the error.
adding `@ganache/console.log` as a dev dependency solved it..

```
node_modules/ganache/dist/ganache.d.ts:5:29 - error TS2307: Cannot find module '@ganache/console.log' or its corresponding type declarations.

5 import { ConsoleLogs } from '@ganache/console.log';
```

**Review by mpetrunic — APPROVED** [review]

**Comment by mpetrunic** [comment]
> If any of you has a clue why the build was failing.. although I didn't touch this part at all. That's the error. adding `@ganache/console.log` as a dev dependency solved it..
> 
> ```
> node_modules/ganache/dist/ganache.d.ts:5:29 - error TS2307: Cannot find module '@ganache/console.log' or its corresponding type declarations.
> 
> 5 import { ConsoleLogs } from '@ganache/console.log';
> ```

Probably ganache bumped version and it's missing dependency

**Review by BeroBurny — APPROVED** [review]
LGTM

**Comment by Tbaut** [comment]
Great, I'll wait a bit before merging, so as not to pollute the review of the other PR.

**Pull request merged**
