### PR TITLE
feat: set default headless mode

### PR DESCRIPTION
**Pull request by Lykhoyda**
Set headless version true as a default parameter
**Short description of work done**

### PR Checklist

- [x] I have run linter locally
- [x] I have run unit and integration tests locally
  - [ ] Update configuration the newest version (readme and const)
- [x] Rebased to master branch / merged master

### Changes

- _EXAMPLE - Removed basic auth from the controller_

### Issues

Closes #

### CODE REVIEW

**Review by BeroBurny — COMMENTED** [review]
I think that `headless` option can be "merged", I don't see the point of having it separated

**Comment by Lykhoyda** [comment]
> I think that `headless` option can be "merged", I don't see the point of having it separated

I didn't get your idea. Do you mean making it a parameter outside the puppeteer and playwright configuration? As a generic for both?

**Comment by BeroBurny** [comment]
> > I think that `headless` option can be "merged", I don't see the point of having it separated
> 
> I didn't get your idea. Do you mean making it a parameter outside the puppeteer and playwright configuration? As a generic for both?

yup

**Comment by BeroBurny** [comment]
> > I think that `headless` option can be "merged", I don't see the point of having it separated
> 
> I didn't get your idea. Do you mean making it a parameter outside the puppeteer and playwright configuration? As a generic for both?

yup

**Review by irubido — APPROVED** [review]

**Review by BeroBurny — APPROVED** [review]
LGTM

**Pull request merged**
