### PR TITLE
chore: merge unstable into master

### PR DESCRIPTION
**Pull request by mpetrunic**
**Short description of work done**

### PR Checklist

- [ ] I have run linter locally
- [ ] I have run unit and integration tests locally
  - [ ] Update configuration the newest version (readme and const)
- [ ] Rebased to master branch / merged master

### Changes

- _EXAMPLE - Removed basic auth from the controller_

### Issues

Closes #

### CODE REVIEW

**Comment by mpetrunic** [comment]
Will release manually from unstable as we have a couple of P0 issues that will create breaking changes as well.

**Comment by mpetrunic** [comment]
> @mpetrunic what's the timeline on the release?

You can already try it `@chainsafe/dappeteer@4.0.0-rc.0` or `@chainsafe/dappeteer@beta`

**Review by BeroBurny — APPROVED** [review]
LGTM

**Review by irubido — APPROVED** [review]

**Review by Lykhoyda — APPROVED** [review]
Look good to me for releasing a new major version

**Comment by Tbaut** [comment]
:rocket:

**Pull request merged**
