### PR TITLE
fix: selector issues, useless timeouts, reorganise tests

### PR DESCRIPTION
**Pull request by mpetrunic**
**Short description of work done**

### PR Checklist

- [x] I have run linter locally
- [x] I have run unit and integration tests locally
  - [ ] Update configuration the newest version (readme and const)
- [x] Rebased to master branch / merged master

### Changes

- _EXAMPLE - Removed basic auth from the controller_

### Issues

Closes #

### CODE REVIEW

**Review by BeroBurny — COMMENTED** [review]
LGTM

what is a point of this file => [screenshot.png](https://github.com/ChainSafe/dappeteer/pull/145/files#diff-979380f5b4f4215c1e7c22e6aa43ac2f39f86fd11ac671054b4bb40af6c4f16b)?
my guess it ends up by mistake over here

**Comment by mpetrunic** [comment]
> LGTM
> 
> what is a point of this file => [screenshot.png](https://github.com/ChainSafe/dappeteer/pull/145/files#diff-979380f5b4f4215c1e7c22e6aa43ac2f39f86fd11ac671054b4bb40af6c4f16b)? my guess it ends up by mistake over here

Shouldn't be here after force push. I've added an automatic screenshot that will be uploaded from CI if a test fails. But there are two tests that are falling for no obvious reason.

**Review by BeroBurny — APPROVED** [review]
:tada:

**Comment by mpetrunic** [comment]
Oh freaking hell, finally, let me try to squash those commits so that we don't have ugly history like that 😅

**Pull request merged**
